### ISSUE TITLE
博主,为什么我运行起来删除和修改

### ISSUE THREAD

**Issue by jinbao55** [wonderfulMorty/SheQu#3]
question:97 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at o.<anonymous> (question:97:38)
    at c (layui.js:2:1690)
    at g (layui.js:2:2249)
    at o.use (layui.js:2:2270)
    at deleteQuestion (question:94:15)
    at HTMLAnchorElement.onclick (question:1:1)

**Comment by jinbao55** [comment]
都不能用

**Comment by wonderfulMorty** [comment]
> 都不能用
额。。。。。当初设计的时候没有设计好，删除和修改都要勾选那一行的复选框
